lavalink:
  server:
    sources:
      youtube: false

logging:
  config: classpath:logback.xml

server:
  port: 8081

lofi:
  channel-url: "https://www.youtube.com/@LofiGirl/streams"
  ytdlp-service-url: "http://yt-dlp:8080"