lavalink:
  server:
    sources:
      youtube: false

logging:
  config: classpath:logback.xml

server:
  port: 8081

lofi:
  channel-url: "https://www.youtube.com/@LofiGirl/streams"
  ytdlp-path: "yt-dlp" #change this to the path of yt-dlp for local testing